import './globals.css';
import styles from "./styles.module.css";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Coffee Connoisseur',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.container}>
        {children}
      </body>
    </html>
  )
}
