import './globals.css';
import styles from "./styles.module.css";

import Head from "next/head";

export const metadata = {
  title: 'Coffee Connoisseur',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Coffee App</title>
        <link rel="icon" href="/coffee-app/public/favicon.ico" />
      </Head>
      <body className={styles.container}>
        {children}
      </body>
    </html>
  )
}
