import './globals.css';
import styles from "./styles.module.css";

import { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: 'Coffee Connoisseur',
  description: 'Generated by create next app',
}

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className={styles.container}>
        {children}
      </body>
    </html>
  )
}
